# Generated by Django 5.1.1 on 2024-11-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('char', '0002_abilitiesmodel_healthmodel_sizemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.IntegerField()),
                ('bulk', models.IntegerField()),
                ('shoddy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_pieces', models.PositiveIntegerField(default=0)),
                ('silver_pieces', models.PositiveIntegerField(default=0)),
                ('copper_pieces', models.PositiveIntegerField(default=0)),
                ('platinum_pieces', models.PositiveIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='char.charactermodel')),
            ],
        ),
    ]
