# Generated by Django 5.1.1 on 2024-11-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('U', 'Untrained'), ('T', 'Trained'), ('E', 'Expert'), ('M', 'Master'), ('L', 'Legendary')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ability_bonus', models.IntegerField()),
                ('item_bonus', models.IntegerField()),
                ('armor_penalty', models.IntegerField()),
                ('proficiency_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skills.proficiencymodel')),
            ],
        ),
    ]
