# Generated by Django 5.1.1 on 2024-11-04 19:22

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='HealthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField()),
                ('current', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('dying', models.BooleanField(default=False)),
                ('wounded', models.BooleanField(default=False)),
                ('resist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('immunities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan')])),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.CreateModel(
            name='RaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hit_points', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('special', models.CharField(max_length=150)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='char.sizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('hero_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('alignment', models.CharField(blank=True, choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('TN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='TN', max_length=2, null=True)),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character', to='char.abilitiesmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character', to='char.healthmodel')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character', to='char.racemodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character', to='char.sizemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
