# Generated by Django 5.1.1 on 2024-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0002_abilitiesmodel_healthmodel_sizemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeritageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('universal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('U', 'Untrained'), ('T', 'Trained'), ('E', 'Expert'), ('M', 'Master'), ('L', 'Legendary')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('bonus', models.IntegerField()),
            ],
        ),
    ]
